### ISSUE TITLE
请问400错误的原因是？

### ISSUE THREAD

**Issue by moleoxa** [starudream/clash-speedtest#25]
环境： Windows 11 + Clash for Windows v0.20.39

 clash-speedtest --clash-addr "http://127.0.0.1:29090" --clash-secret "my_key" --clash-proxy "127.0.0.1:27890"

ERR test error: response status 400 Bad Request

**Comment by starudream** [comment]
`--clash-proxy`

需要加上协议类型，如：`http://127.0.0.1:7890` `socks5://127.0.0.1:7890`
